[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ramms"
version = "0.1.0"
description = "A Python package for modeling and analyzing reconfigurable architected mechanical metamaterials."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "sympy",
    "matplotlib",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]